import React from "react";
import { IArticuloInsumo } from "../../types/entities/IArticuloInsumo";

  {/*BORRAR UNA VEZ FUNCIONE LA API */}
  export const insumosHardcode:IArticuloInsumo[] = [
    {
      id: 1,
      denominacion: "Harina 000",
      precioVenta: 500,
      precioCompra: 350,
      unidadMedidaEnum: "kg",
      stockActual: 25,
      stockMaximo: 100,
      stockMinimo: 10,
      esParaPreparar: true,
      esVendible: false,
      productoActivo: true,
      tiempoEstimadoMinutos: 0,
      idSucursal: 1,
      idCategoria: 1,
    },
    {
      id: 2,
      denominacion: "Azúcar",
      precioVenta: 450,
      precioCompra: 300,
      unidadMedidaEnum: "kg",
      stockActual: 15,
      stockMaximo: 80,
      stockMinimo: 5,
      esParaPreparar: true,
      esVendible: false,
      productoActivo: true,
      tiempoEstimadoMinutos: 0,
      idSucursal: 1,
      idCategoria: 1,
    },
    {
      id: 3,
      denominacion: "Coca-Cola 1.5L",
      precioVenta: 900,
      precioCompra: 650,
      unidadMedidaEnum: "unidad",
      stockActual: 60,
      stockMaximo: 120,
      stockMinimo: 20,
      esParaPreparar: false,
      esVendible: true,
      productoActivo: true,
      tiempoEstimadoMinutos: 0,
      idSucursal: 1,
      idCategoria: 1,
    },
    {
      id: 4,
      denominacion: "Caja de huevos (12u)",
      precioVenta: 800,
      precioCompra: 550,
      unidadMedidaEnum: "unidad",
      stockActual: 40,
      stockMaximo: 100,
      stockMinimo: 10,
      esParaPreparar: true,
      esVendible: false,
      productoActivo: true,
      tiempoEstimadoMinutos: 0,
      idSucursal: 1,
      idCategoria: 1,
    },
    {
      id: 5,
      denominacion: "Pan de hamburguesa",
      precioVenta: 700,
      precioCompra: 480,
      unidadMedidaEnum: "unidad",
      stockActual: 30,
      stockMaximo: 90,
      stockMinimo: 15,
      esParaPreparar: true,
      esVendible: true,
      productoActivo: true,
      tiempoEstimadoMinutos: 0,
      idSucursal: 1,
      idCategoria: 1,
    }
  ];
  